"""
Semantic RAG retriever implementation.

Uses sentence-transformer embeddings to retrieve memories by cosine
similarity against a query generated by the LLM.
"""

import logging
from typing import List, Optional
from datetime import datetime

from rag.base import BaseRetriever, Memory as RAGMemory, RetrievalResult
from database.repository import Repository
from database.models import Memory as DBMemory
from memory.embedder import MemoryEmbedder
from memory.tag_embedder import TagEmbedder

logger = logging.getLogger(__name__)


class SemanticRetriever(BaseRetriever):
    """
    Retrieves memories using semantic similarity between a query
    and stored memory statement embeddings.
    
    On retrieval:
    1. Embeds the query using the sentence-transformer model
    2. Loads all active memories for the user (with embeddings)
    3. Back-fills embeddings for memories missing them
    4. Computes cosine similarity
    5. Returns top-k above threshold, capped at limit
    """
    
    def __init__(
        self,
        repository: Repository,
        tag_embedder: TagEmbedder,
        similarity_threshold: float = 0.3
    ):
        """
        Initialize the semantic retriever.
        
        Args:
            repository: Database repository for memory access
            tag_embedder: TagEmbedder instance (shares the sentence-transformer model)
            similarity_threshold: Minimum cosine similarity to include a memory
        """
        self.repository = repository
        self.tag_embedder = tag_embedder
        self.memory_embedder = MemoryEmbedder(tag_embedder)
        self.similarity_threshold = similarity_threshold
    
    @property
    def retriever_type(self) -> str:
        """Return the type of this retriever."""
        return "semantic"
    
    def _ensure_embeddings(self, memories: List[DBMemory]) -> List[DBMemory]:
        """
        Ensure all memories have embeddings, back-filling any that are missing.
        
        This handles the case where memories were created before semantic
        retrieval was enabled (e.g., switching from RAG_MODE=none to semantic).
        
        Args:
            memories: List of Memory instances (some may lack embeddings)
            
        Returns:
            Same list with embeddings guaranteed to be present
        """
        missing = [m for m in memories if m.embedding is None]
        if not missing:
            return memories
        
        logger.info(f"Back-filling embeddings for {len(missing)} memories")
        statements = [m.statement for m in missing]
        embeddings = self.memory_embedder.embed_statements_batch(statements)
        
        for memory, embedding in zip(missing, embeddings):
            blob = MemoryEmbedder.serialize_embedding(embedding)
            self.repository.update_memory_embedding(memory.id, blob)
            memory.embedding = blob
        
        return memories
    
    def _db_memory_to_rag_memory(self, db_mem: DBMemory, score: float) -> RAGMemory:
        """
        Convert a database Memory to a RAG Memory dataclass.
        
        Args:
            db_mem: Database Memory instance
            score: Similarity score for this memory
            
        Returns:
            RAG Memory dataclass instance
        """
        tags = db_mem.get_tags()
        return RAGMemory(
            memory_id=str(db_mem.id),
            text=db_mem.statement,
            memory_type=db_mem.memory_type,
            timestamp=db_mem.created_at,
            polarity=0.0,
            confidence=score,
            entities=[],
            topics=tags,
            metadata={
                "db_id": db_mem.id,
                "tags": tags,
                "similarity_score": score
            }
        )
    
    def retrieve(self, query: str, limit: int = 10, **kwargs) -> RetrievalResult:
        """
        Retrieve relevant memories for a query using semantic similarity.
        
        Args:
            query: Search query (generated by the LLM)
            limit: Maximum number of memories to retrieve
            **kwargs: Must include 'user_id' (int)
            
        Returns:
            RetrievalResult containing the retrieved memories
        """
        user_id = kwargs.get("user_id")
        if user_id is None:
            logger.warning("SemanticRetriever.retrieve() called without user_id")
            return RetrievalResult(
                memories=[], retriever_type=self.retriever_type, query=query
            )
        
        # Get all active memories for this user
        all_memories = self.repository.get_user_active_memories_with_embeddings(user_id)
        
        if not all_memories:
            return RetrievalResult(
                memories=[], retriever_type=self.retriever_type, query=query,
                metadata={"total_memories": 0}
            )
        
        # Ensure all memories have embeddings
        all_memories = self._ensure_embeddings(all_memories)
        
        # Embed the query
        query_embedding = self.memory_embedder.embed_statement(query)
        
        # Deserialize memory embeddings and compute similarities
        memory_embeddings = []
        valid_memories = []
        for mem in all_memories:
            if mem.embedding is not None:
                try:
                    emb = MemoryEmbedder.deserialize_embedding(mem.embedding)
                    memory_embeddings.append(emb)
                    valid_memories.append(mem)
                except Exception:
                    logger.warning(f"Failed to deserialize embedding for memory {mem.id}")
        
        if not valid_memories:
            return RetrievalResult(
                memories=[], retriever_type=self.retriever_type, query=query,
                metadata={"total_memories": len(all_memories), "valid_embeddings": 0}
            )
        
        # Compute cosine similarities
        scores = MemoryEmbedder.cosine_similarity_batch(query_embedding, memory_embeddings)
        
        # Pair memories with scores, filter by threshold, sort by score desc
        scored = list(zip(valid_memories, scores))
        scored = [(m, s) for m, s in scored if s >= self.similarity_threshold]
        scored.sort(key=lambda x: x[1], reverse=True)
        
        # Cap at limit
        scored = scored[:limit]
        
        # Convert to RAG Memory objects
        rag_memories = [
            self._db_memory_to_rag_memory(db_mem, score)
            for db_mem, score in scored
        ]
        
        return RetrievalResult(
            memories=rag_memories,
            retriever_type=self.retriever_type,
            query=query,
            metadata={
                "total_memories": len(all_memories),
                "above_threshold": len(scored),
                "similarity_threshold": self.similarity_threshold
            }
        )
    
    def retrieve_db_memories(self, query: str, limit: int = 10, user_id: Optional[int] = None) -> List[DBMemory]:
        """
        Convenience method that returns database Memory objects directly
        (instead of RAG Memory dataclasses). Used by GraphRetriever
        and ConversationManager.
        
        Args:
            query: Search query
            limit: Maximum number of memories to return
            user_id: User ID
            
        Returns:
            List of database Memory instances sorted by similarity desc
        """
        if user_id is None:
            return []
        
        all_memories = self.repository.get_user_active_memories_with_embeddings(user_id)
        if not all_memories:
            return []
        
        all_memories = self._ensure_embeddings(all_memories)
        query_embedding = self.memory_embedder.embed_statement(query)
        
        memory_embeddings = []
        valid_memories = []
        for mem in all_memories:
            if mem.embedding is not None:
                try:
                    emb = MemoryEmbedder.deserialize_embedding(mem.embedding)
                    memory_embeddings.append(emb)
                    valid_memories.append(mem)
                except Exception:
                    pass
        
        if not valid_memories:
            return []
        
        scores = MemoryEmbedder.cosine_similarity_batch(query_embedding, memory_embeddings)
        scored = [(m, s) for m, s in zip(valid_memories, scores) if s >= self.similarity_threshold]
        scored.sort(key=lambda x: x[1], reverse=True)
        
        return [m for m, _ in scored[:limit]]
    
    def add_memory(self, memory: RAGMemory) -> None:
        """
        No-op: memories are added via the repository directly.
        Embedding generation is handled in the consolidation pipeline.
        """
        pass
